sudo: false
language: node_js
node_js:
- '8'
- '10'
- '12'
- '13'
matrix:
  include:
  - node_js: node
    env: BROWSERS=1
git:
  depth: 1
notifications:
  irc: irc.freenode.org#socket.io
install:
- npm ci
- npm run bootstrap
env:
  global:
  - secure: KBqm/kqdp4A3igys6+5Ec4zF4e0KAb/f4Sh2nPDbLwd6Oye1oOGjdgczZlgU7KE/CcogreJ0hYGLDYI0xy7D2+nF04q6HQPNZEUlF3DbWXAO3kJaM9hGmRGN9kwYgAtVV0CEZFH7wlp5xhm90e1x/WPFthBQgtr85mFOU+PxBWc=
  - secure: QvF391qWc3BESOiWbiRAQqeoiYWFiGXeMnH8aMkwpS01xWxUYZhSoEyqUirvoW3xmV64dXQflriONkCbYZHzLCR4xoPMgueRyboaeSa/JOgz+Ent+3lPTE5gMHaHq7RFV1d3s9Fse9Hd41RsNS+VzLGepSdnCMCkvTk5Eso1GIc=
  - secure: E9kGKmwCNO2FSZxHFjoQ/Ar0XO1b8/NSYFEqVlMjeVw5MzaIP1rZ+7ELhzV1iRfpFTM7fxX2E96A3aqZPz65RKCXf9e4nX9Vvua8s5h74+M47uVPD+S720rcu1oQwg8AlUIczD8+Vni66aEbETAnMpXG5T8gcjzIdNkiA8O9Dj4=
